### ISSUE TITLE
Need .Net calls to ReMap the hosts

### ISSUE THREAD

**Issue by RameshJhajharia** [AutomatedTester/AutomatedTester.BrowserMob#1]
Can you please provide .Net calls to ReMap the hosts ?
As we have REST API call "POST /proxy/[port]/hosts" but for this we don't have .net wrapped calls.
Can you please help me on this or guide me so I can do this?

**Comment by AdaTheDev** [comment]
Should be straight forward - new method to go in Client.cs taking a host and ip address. Currently having issues running WebDriver with FF 18 on my machine so need to resolve that before I can test the changes.

**Comment by RameshJhajharia** [comment]
Thanks Adrian,

Waiting eagerly for new release as I tried but couldn't succeed.

**Comment by RameshJhajharia** [comment]
Thanks Adrian,

Waiting eagerly for new release as I tried but couldn't succeed.

On Fri, Jan 11, 2013 at 3:13 PM, Adrian Hills notifications@github.comwrote:

> Should be straight forward - new method to go in Client.cs taking a host
> and ip address. Currently having issues running WebDriver with FF 18 on my
> machine so need to resolve that before I can test the changes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/AutomatedTester/AutomatedTester.BrowserMob/issues/1#issuecomment-12137531.

## 

Ramesh Kumar Jhajharia

**Comment by AdaTheDev** [comment]
Looks like this particular method in the REST API was not added until after the currently available built version of BrowserMob Proxy (Beta 6) - I get a 404. But sounds like building from source will bring that in, per  https://groups.google.com/forum/?fromgroups=#!topic/browsermob-proxy/-yTDP_gaflo

**Comment by AdaTheDev** [comment]
RemapHost method added to Client.cs. Points to note:
1) you need to be running at least Beta 7 of BrowserMob proxy (current latest version at time of writing) - the pre-built version currently available is Beta 6 which does not include the REST API for remapping hosts, so you will currently need to build yourself.
2) whereas the examples I found gave example arguments of the nature "{something}.com", I found in testing this had no effect. Instead, giving the host as "www.{something}.com" worked

**Comment by RameshJhajharia** [comment]
I tried with new code but getting 404 . I am attaching snap shot of the issue also.
I used following call for this :
client.RemapHost("www.test.com", "127.0.0.1");

Please find attached snap shot for more details.
![BrowserMob Exception](https://f.cloud.github.com/assets/2621894/64312/faa25c9a-5e3d-11e2-9ab6-81a0c8e92e24.png)

**Comment by AdaTheDev** [comment]
Per my last comment and the linked forum post, you need to make sure you have the latest BrowserMob Proxy code (which you'll need to build from source as the latest zip download via http://opensource.webmetrics.com/browsermob-proxy/ is Beta 6 version, whereby latest is Beta 7 - the Beta 6 did not have the REST API to remap hosts)

**Comment by RameshJhajharia** [comment]
Thanks a lot.

Its working perfectly now.
