### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by z41** [AutomatedTester/AutomatedTester.BrowserMob#2]
Hello, David.
Thanks for this tool!
Sorry, that I contact you by creating this issue (I haven't found another way to do it on gitHub). There is no information about license for browser mob .net wrapper. Can you add one? 
Thanks in advance!

**Comment by ronytabh** [comment]
Hi David,

I am not seeing the option to add setCaptureHeaders and setCaptureContent as we have it in the Java version, this is causing an issue like when I am trying to capture the Har data when there is a click event I am not seeing the complete traffic as I am seeing when doing GotoUrl in Selenium.
